name: Build Image

#on:
#  workflow_dispatch:
#  repository_dispatch:
#    types: build_docker_image
on: 
  workflow_dispatch:
    inputs:
      img-tag:
        description: 'image tag'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 拉取master分支
      - name: Checkout
        uses: actions/checkout@master
      # 设置qemu来编译多个平台的镜像
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # 设置buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # 登陆dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 编译并且推送到dockerhub
      - name: 构建并推送到 Dockerhub 镜像仓库
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.1.10.0 # Dockerfile 位置
          platforms: linux/amd64
          push: true
          #设置推送的仓库
          tags: |
            unkwner/wenet_train_env:${{ github.event.inputs.img-tag }}
